version: "3"

volumes:
  backend_volume:

services:
  frontend:
    image: trixis/cultr_frontend
    restart: always
    ports:
      - 80:80
      - 443:443

  backend:
    build: ./
    restart: always
    environment:
      - CORS_ORIGINS=["http://localhost:8000", "http://localhost:3000", "http://localhost:5000", "http://127.0.0.1", "http://127.0.0.1:5000"]
      - DATABASE_URI=sqlite+aiosqlite:////resources/database.db
    ports:
      - 5000:5000
    volumes:
      - backend_volume:/resources
